    var ninaSlingbackBtn = document.getElementById('nina-btn');
    var renaStilettoBtn = document.getElementById('rena-btn');
    var remyAnkleBtn = document.getElementById('remy-btn');
    var classicFlatBtn = document.getElementById('classic-flat-btn');
    var muleBtn = document.getElementById('mule-btn');
    var anklebootBtn = document.getElementById('ankleboot-btn');
    var ssBtn = document.getElementById('ss-btn');
    var psBtn = document.getElementById('ps-btn');
    var fbmBtn = document.getElementById('fbm-btn');
    var rtsBtn = document.getElementById('rts-btn');
    var rtabBtn = document.getElementById('rtab-btn');
    var lilyBtn = document.getElementById('lily-btn');
    var lisaBtn = document.getElementById('lisa-btn');
    var daraBtn = document.getElementById('dara-btn');
    var mollyBtn = document.getElementById('molly-btn');
    var coletteBtn = document.getElementById('colette-btn');
    var laurenBtn = document.getElementById('lauren-btn');

    var ninaDiv = document.getElementById('nina-div');
    var renaDiv = document.getElementById('rena-div') ;
    var remyDiv = document.getElementById('remy-div');
    var classicFlatDiv = document.getElementById('classicflat-div');
    var muleDiv = document.getElementById('mule-div');
    var anklebootDiv = document.getElementById('ankleboot-div');
    var ssDiv = document.getElementById('ss-div');
    var psDiv = document.getElementById('ps-div');
    var fbmDiv = document.getElementById('fbm-div');
    var rtsDiv = document.getElementById('rts-div');
    var rtabDiv = document.getElementById('rtab-div');
    var lilyDiv = document.getElementById('lily-div');
    var lisaDiv = document.getElementById('lisa-div');
    var daraDiv = document.getElementById('dara-div');
    var mollyDiv = document.getElementById('molly-div');
    var coletteDiv = document.getElementById('colette-div');
    var laurenDiv = document.getElementById('lauren-div');

    ninaSlingbackBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'visible');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'selected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected');
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected');
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };

    renaStilettoBtn.onclick = function() {
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        renaDiv.setAttribute('class', 'visible');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'selected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected');  
        rtabBtn.setAttribute('class', 'unselected'); 
        lilyBtn.setAttribute('class', 'unselected');  
        lisaBtn.setAttribute('class', 'unselected');  
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };

    remyAnkleBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'visible');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'selected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected');  
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');  
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraDiv.setAttribute('class', 'hidden');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };

    classicFlatBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'visible');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');
        
        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'selected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };

    muleBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'visible');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'selected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    }; 

    anklebootBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'visible');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'selected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    }; 

    ssBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'visible');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'selected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    }; 

    psBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'visible');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'selected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected');
        rtabBtn.setAttribute('class', 'unselected'); 
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };   

    fbmBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'visible');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'selected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };         

    rtsBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'visible');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'selected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    }; 

    rtabBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'visible');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'selected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    }; 

    lilyBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'visible');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'selected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };

    lisaBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'visible');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'selected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };  

    daraBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'visible');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'selected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };    

    mollyBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'visible');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'selected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'unselected');
    };  

    coletteBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'visible');
        laurenDiv.setAttribute('class', 'hidden');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'selected');
        laurenBtn.setAttribute('class', 'unselected');
    };  

    laurenBtn.onclick = function() {
        renaDiv.setAttribute('class', 'hidden');
        remyDiv.setAttribute('class', 'hidden');
        classicFlatDiv.setAttribute('class', 'hidden');
        ninaDiv.setAttribute('class', 'hidden');
        muleDiv.setAttribute('class', 'hidden');
        anklebootDiv.setAttribute('class', 'hidden');
        ssDiv.setAttribute('class', 'hidden');
        rtabDiv.setAttribute('class', 'hidden');
        psDiv.setAttribute('class', 'hidden');
        fbmDiv.setAttribute('class', 'hidden');
        rtsDiv.setAttribute('class', 'hidden');
        lilyDiv.setAttribute('class', 'hidden');
        lisaDiv.setAttribute('class', 'hidden');
        daraDiv.setAttribute('class', 'hidden');
        mollyDiv.setAttribute('class', 'hidden');
        coletteDiv.setAttribute('class', 'hidden');
        laurenDiv.setAttribute('class', 'visible');

        ninaSlingbackBtn.setAttribute('class', 'unselected');
        renaStilettoBtn.setAttribute('class', 'unselected');
        remyAnkleBtn.setAttribute('class', 'unselected');
        classicFlatBtn.setAttribute('class', 'unselected');
        muleBtn.setAttribute('class', 'unselected'); 
        anklebootBtn.setAttribute('class', 'unselected');
        ssBtn.setAttribute('class', 'unselected');
        psBtn.setAttribute('class', 'unselected');
        fbmBtn.setAttribute('class', 'unselected');
        rtsBtn.setAttribute('class', 'unselected'); 
        rtabBtn.setAttribute('class', 'unselected');
        lilyBtn.setAttribute('class', 'unselected');
        lisaBtn.setAttribute('class', 'unselected');
        daraBtn.setAttribute('class', 'unselected');
        mollyBtn.setAttribute('class', 'unselected');
        coletteBtn.setAttribute('class', 'unselected');
        laurenBtn.setAttribute('class', 'selected');
    };    
